margarita_results = {'drinks': [{'idDrink': '11007',
   'strDrink': 'Margarita',
   'strDrinkAlternate': None,
   'strTags': 'IBA,ContemporaryClassic',
   'strVideo': None,
   'strCategory': 'Ordinary Drink',
   'strIBA': 'Contemporary Classics',
   'strAlcoholic': 'Alcoholic',
   'strGlass': 'Cocktail glass',
   'strInstructions': 'Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.',
   'strInstructionsES': None,
   'strInstructionsDE': 'Reiben Sie den Rand des Glases mit der Limettenscheibe, damit das Salz daran haftet. Achten Sie darauf, dass nur der äußere Rand angefeuchtet wird und streuen Sie das Salz darauf. Das Salz sollte sich auf den Lippen des Genießers befinden und niemals in den Cocktail einmischen. Die anderen Zutaten mit Eis schütteln und vorsichtig in das Glas geben.',
   'strInstructionsFR': None,
   'strInstructionsIT': 'Strofina il bordo del bicchiere con la fetta di lime per far aderire il sale.\r\nAvere cura di inumidire solo il bordo esterno e cospargere di sale.\r\nIl sale dovrebbe presentarsi alle labbra del bevitore e non mescolarsi mai al cocktail.\r\nShakerare gli altri ingredienti con ghiaccio, quindi versarli delicatamente nel bicchiere.',
   'strInstructionsZH-HANS': None,
   'strInstructionsZH-HANT': None,
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg',
   'strIngredient1': 'Tequila',
   'strIngredient2': 'Triple sec',
   'strIngredient3': 'Lime juice',
   'strIngredient4': 'Salt',
   'strIngredient5': None,
   'strIngredient6': None,
   'strIngredient7': None,
   'strIngredient8': None,
   'strIngredient9': None,
   'strIngredient10': None,
   'strIngredient11': None,
   'strIngredient12': None,
   'strIngredient13': None,
   'strIngredient14': None,
   'strIngredient15': None,
   'strMeasure1': '1 1/2 oz ',
   'strMeasure2': '1/2 oz ',
   'strMeasure3': '1 oz ',
   'strMeasure4': None,
   'strMeasure5': None,
   'strMeasure6': None,
   'strMeasure7': None,
   'strMeasure8': None,
   'strMeasure9': None,
   'strMeasure10': None,
   'strMeasure11': None,
   'strMeasure12': None,
   'strMeasure13': None,
   'strMeasure14': None,
   'strMeasure15': None,
   'strImageSource': 'https://commons.wikimedia.org/wiki/File:Klassiche_Margarita.jpg',
   'strImageAttribution': 'Cocktailmarler',
   'strCreativeCommonsConfirmed': 'Yes',
   'dateModified': '2015-08-18 14:42:59'},
  {'idDrink': '11118',
   'strDrink': 'Blue Margarita',
   'strDrinkAlternate': None,
   'strTags': None,
   'strVideo': None,
   'strCategory': 'Ordinary Drink',
   'strIBA': None,
   'strAlcoholic': 'Alcoholic',
   'strGlass': 'Cocktail glass',
   'strInstructions': 'Rub rim of cocktail glass with lime juice. Dip rim in coarse salt. Shake tequila, blue curacao, and lime juice with ice, strain into the salt-rimmed glass, and serve.',
   'strInstructionsES': None,
   'strInstructionsDE': 'Den Rand des Cocktailglases mit Limettensaft einreiben. Den Rand in grobes Salz tauchen. Tequila, blauen Curacao und Limettensaft mit Eis schütteln, in das mit Salz umhüllte Glas abseihen und servieren.',
   'strInstructionsFR': None,
   'strInstructionsIT': 'Strofinare il bordo del bicchiere da cocktail con succo di lime. Immergere il bordo nel sale grosso. Shakerare tequila, blue curacao e succo di lime con ghiaccio, filtrare nel bicchiere bordato di sale e servire.',
   'strInstructionsZH-HANS': None,
   'strInstructionsZH-HANT': None,
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/bry4qh1582751040.jpg',
   'strIngredient1': 'Tequila',
   'strIngredient2': 'Blue Curacao',
   'strIngredient3': 'Lime juice',
   'strIngredient4': 'Salt',
   'strIngredient5': None,
   'strIngredient6': None,
   'strIngredient7': None,
   'strIngredient8': None,
   'strIngredient9': None,
   'strIngredient10': None,
   'strIngredient11': None,
   'strIngredient12': None,
   'strIngredient13': None,
   'strIngredient14': None,
   'strIngredient15': None,
   'strMeasure1': '1 1/2 oz ',
   'strMeasure2': '1 oz ',
   'strMeasure3': '1 oz ',
   'strMeasure4': 'Coarse ',
   'strMeasure5': None,
   'strMeasure6': None,
   'strMeasure7': None,
   'strMeasure8': None,
   'strMeasure9': None,
   'strMeasure10': None,
   'strMeasure11': None,
   'strMeasure12': None,
   'strMeasure13': None,
   'strMeasure14': None,
   'strMeasure15': None,
   'strImageSource': None,
   'strImageAttribution': None,
   'strCreativeCommonsConfirmed': 'Yes',
   'dateModified': '2015-08-18 14:51:53'},
  {'idDrink': '17216',
   'strDrink': "Tommy's Margarita",
   'strDrinkAlternate': None,
   'strTags': 'IBA,NewEra',
   'strVideo': None,
   'strCategory': 'Ordinary Drink',
   'strIBA': 'New Era Drinks',
   'strAlcoholic': 'Alcoholic',
   'strGlass': 'Old-Fashioned glass',
   'strInstructions': 'Shake and strain into a chilled cocktail glass.',
   'strInstructionsES': None,
   'strInstructionsDE': 'Schütteln und in ein gekühltes Cocktailglas abseihen.',
   'strInstructionsFR': None,
   'strInstructionsIT': 'Shakerare e filtrare in una coppetta da cocktail ghiacciata.',
   'strInstructionsZH-HANS': None,
   'strInstructionsZH-HANT': None,
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/loezxn1504373874.jpg',
   'strIngredient1': 'Tequila',
   'strIngredient2': 'Lime Juice',
   'strIngredient3': 'Agave syrup',
   'strIngredient4': None,
   'strIngredient5': None,
   'strIngredient6': None,
   'strIngredient7': None,
   'strIngredient8': None,
   'strIngredient9': None,
   'strIngredient10': None,
   'strIngredient11': None,
   'strIngredient12': None,
   'strIngredient13': None,
   'strIngredient14': None,
   'strIngredient15': None,
   'strMeasure1': '4.5 cl',
   'strMeasure2': '1.5 cl',
   'strMeasure3': '2 spoons',
   'strMeasure4': None,
   'strMeasure5': None,
   'strMeasure6': None,
   'strMeasure7': None,
   'strMeasure8': None,
   'strMeasure9': None,
   'strMeasure10': None,
   'strMeasure11': None,
   'strMeasure12': None,
   'strMeasure13': None,
   'strMeasure14': None,
   'strMeasure15': None,
   'strImageSource': None,
   'strImageAttribution': None,
   'strCreativeCommonsConfirmed': 'No',
   'dateModified': '2017-09-02 18:37:54'},
  {'idDrink': '16158',
   'strDrink': 'Whitecap Margarita',
   'strDrinkAlternate': None,
   'strTags': None,
   'strVideo': None,
   'strCategory': 'Other / Unknown',
   'strIBA': None,
   'strAlcoholic': 'Alcoholic',
   'strGlass': 'Margarita/Coupette glass',
   'strInstructions': 'Place all ingredients in a blender and blend until smooth. This makes one drink.',
   'strInstructionsES': None,
   'strInstructionsDE': 'Alle Zutaten in einen Mixer geben und mischen.',
   'strInstructionsFR': None,
   'strInstructionsIT': 'Metti tutti gli ingredienti in un frullatore e frulla fino a che non diventa liscio.',
   'strInstructionsZH-HANS': None,
   'strInstructionsZH-HANT': None,
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/srpxxp1441209622.jpg',
   'strIngredient1': 'Ice',
   'strIngredient2': 'Tequila',
   'strIngredient3': 'Cream of coconut',
   'strIngredient4': 'Lime juice',
   'strIngredient5': None,
   'strIngredient6': None,
   'strIngredient7': None,
   'strIngredient8': None,
   'strIngredient9': None,
   'strIngredient10': None,
   'strIngredient11': None,
   'strIngredient12': None,
   'strIngredient13': None,
   'strIngredient14': None,
   'strIngredient15': None,
   'strMeasure1': '1 cup ',
   'strMeasure2': '2 oz ',
   'strMeasure3': '1/4 cup ',
   'strMeasure4': '3 tblsp fresh ',
   'strMeasure5': None,
   'strMeasure6': None,
   'strMeasure7': None,
   'strMeasure8': None,
   'strMeasure9': None,
   'strMeasure10': None,
   'strMeasure11': None,
   'strMeasure12': None,
   'strMeasure13': None,
   'strMeasure14': None,
   'strMeasure15': None,
   'strImageSource': None,
   'strImageAttribution': None,
   'strCreativeCommonsConfirmed': 'No',
   'dateModified': '2015-09-02 17:00:22'},
  {'idDrink': '12322',
   'strDrink': 'Strawberry Margarita',
   'strDrinkAlternate': None,
   'strTags': None,
   'strVideo': None,
   'strCategory': 'Ordinary Drink',
   'strIBA': None,
   'strAlcoholic': 'Alcoholic',
   'strGlass': 'Cocktail glass',
   'strInstructions': 'Rub rim of cocktail glass with lemon juice and dip rim in salt. Shake schnapps, tequila, triple sec, lemon juice, and strawberries with ice, strain into the salt-rimmed glass, and serve.',
   'strInstructionsES': None,
   'strInstructionsDE': 'Cocktailglasrand mit Zitronensaft und Tauchrand in Salz wenden. Schnaps, Tequila, Triple-Sec, Zitronensaft und Erdbeeren mit Eis schütteln, in das salzige Glas sieben und servieren.',
   'strInstructionsFR': None,
   'strInstructionsIT': 'Strofinare il bordo del bicchiere da cocktail con succo di limone e immergerlo nel sale. Shakerare grappa, tequila, triple sec, succo di limone e fragole con ghiaccio, filtrare nel bicchiere bordato di sale e servire.',
   'strInstructionsZH-HANS': None,
   'strInstructionsZH-HANT': None,
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tqyrpw1439905311.jpg',
   'strIngredient1': 'Strawberry schnapps',
   'strIngredient2': 'Tequila',
   'strIngredient3': 'Triple sec',
   'strIngredient4': 'Lemon juice',
   'strIngredient5': 'Strawberries',
   'strIngredient6': 'Salt',
   'strIngredient7': None,
   'strIngredient8': None,
   'strIngredient9': None,
   'strIngredient10': None,
   'strIngredient11': None,
   'strIngredient12': None,
   'strIngredient13': None,
   'strIngredient14': None,
   'strIngredient15': None,
   'strMeasure1': '1/2 oz ',
   'strMeasure2': '1 oz ',
   'strMeasure3': '1/2 oz ',
   'strMeasure4': '1 oz ',
   'strMeasure5': '1 oz ',
   'strMeasure6': None,
   'strMeasure7': None,
   'strMeasure8': None,
   'strMeasure9': None,
   'strMeasure10': None,
   'strMeasure11': None,
   'strMeasure12': None,
   'strMeasure13': None,
   'strMeasure14': None,
   'strMeasure15': None,
   'strImageSource': None,
   'strImageAttribution': None,
   'strCreativeCommonsConfirmed': 'No',
   'dateModified': '2015-08-18 14:41:51'},
  {'idDrink': '178332',
   'strDrink': 'Smashed Watermelon Margarita',
   'strDrinkAlternate': None,
   'strTags': None,
   'strVideo': None,
   'strCategory': 'Cocktail',
   'strIBA': None,
   'strAlcoholic': 'Alcoholic',
   'strGlass': 'Collins glass',
   'strInstructions': 'In a mason jar muddle the watermelon and 5 mint leaves together into a puree and strain. Next add the grapefruit juice, juice of half a lime and the tequila as well as some ice. Put a lid on the jar and shake. Pour into a glass and add more ice. Garnish with fresh mint and a small slice of watermelon.',
   'strInstructionsES': None,
   'strInstructionsDE': None,
   'strInstructionsFR': None,
   'strInstructionsIT': "In un barattolo di vetro pestare l'anguria e 5 foglie di menta insieme, filtrare il contenuto in un bicchiere. Quindi aggiungere il succo di pompelmo, il succo di mezzo lime, la tequila e un po 'di ghiaccio. Metti un coperchio sul barattolo e agita. Versare in un bicchiere e aggiungere altro ghiaccio. Guarnire con menta fresca e una fettina di anguria.",
   'strInstructionsZH-HANS': None,
   'strInstructionsZH-HANT': None,
   'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/dztcv51598717861.jpg',
   'strIngredient1': 'Watermelon',
   'strIngredient2': 'Mint',
   'strIngredient3': 'Grapefruit Juice',
   'strIngredient4': 'Lime',
   'strIngredient5': 'Tequila',
   'strIngredient6': 'Watermelon',
   'strIngredient7': 'Mint',
   'strIngredient8': None,
   'strIngredient9': None,
   'strIngredient10': None,
   'strIngredient11': None,
   'strIngredient12': None,
   'strIngredient13': None,
   'strIngredient14': None,
   'strIngredient15': None,
   'strMeasure1': '1/2 cup',
   'strMeasure2': '5',
   'strMeasure3': '1/3 Cup',
   'strMeasure4': 'Juice of 1/2',
   'strMeasure5': '1 shot',
   'strMeasure6': 'Garnish with',
   'strMeasure7': 'Garnish with',
   'strMeasure8': None,
   'strMeasure9': None,
   'strMeasure10': None,
   'strMeasure11': None,
   'strMeasure12': None,
   'strMeasure13': None,
   'strMeasure14': None,
   'strMeasure15': None,
   'strImageSource': None,
   'strImageAttribution': None,
   'strCreativeCommonsConfirmed': 'No',
   'dateModified': None}]}

strawberry_margarita = {'drinks': [{'idDrink': '12322', 'strDrink': 'Strawberry Margarita', 'strDrinkAlternate': None,
 'strTags': None, 'strVideo': None, 'strCategory': 'Ordinary Drink',
  'strIBA': None, 'strAlcoholic': 'Alcoholic',
   'strGlass': 'Cocktail glass', 
   'strInstructions': 'Rub rim of cocktail glass with lemon juice and dip rim in salt. Shake schnapps, tequila, triple sec, lemon juice, and strawberries with ice, strain into the salt-rimmed glass, and serve.', 'strInstructionsES': None,
    'strInstructionsDE': 'Cocktailglasrand mit Zitronensaft und Tauchrand in Salz wenden. Schnaps, Tequila, Triple-Sec, Zitronensaft und Erdbeeren mit Eis schütteln, in das salzige Glas sieben und servieren.', 'strInstructionsFR': None, 'strInstructionsIT': 'Strofinare il bordo del bicchiere da cocktail con succo di limone e immergerlo nel sale. Shakerare grappa, tequila, triple sec, succo di limone e fragole con ghiaccio, filtrare nel bicchiere bordato di sale e servire.', 'strInstructionsZH-HANS': None, 'strInstructionsZH-HANT': None, 'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/tqyrpw1439905311.jpg',
    'strIngredient1': 'Strawberry schnapps',
     'strIngredient2': 'Tequila', 'strIngredient3': 'Triple sec',
      'strIngredient4': 'Lemon juice', 
      'strIngredient5': 'Strawberries', 'strIngredient6': 'Salt', 'strIngredient7': None, 'strIngredient8': None, 
      'strIngredient9': None, 'strIngredient10': None, 
      'strIngredient11': None, 'strIngredient12': None, 'strIngredient13': None,
       'strIngredient14': None, 'strIngredient15': None, 'strMeasure1': '1/2 oz ', 'strMeasure2': '1 oz ', 'strMeasure3': '1/2 oz ', 'strMeasure4': '1 oz ',
    'strMeasure5': '1 oz ', 'strMeasure6': None, 'strMeasure7': None, 'strMeasure8': None, 'strMeasure9': None,
     'strMeasure10': None, 'strMeasure11': None, 'strMeasure12': None, 'strMeasure13': None, 'strMeasure14': None, 'strMeasure15': None,
      'strImageSource': None, 'strImageAttribution': None, 'strCreativeCommonsConfirmed': 'No', 'dateModified': '2015-08-18 14:41:51'}]}

drink_dict_total = strawberry_margarita
drink_dict_access = drink_dict_total['drinks']
drink_ingredients = []
drink_name_and_ingredients = {}
for key, value in drink_dict_access.items():
   if 'strIngredient' in key and value != 'null':
      drink_ingredients.append(value)        
drink_name_and_ingredients= {'name': drink_dict_access['strIngredient'], 'ingredients': drink_ingredients}
